install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - npm install
  - npm install -g

test_script:
  - node --version
  - npm --version
  - cmd: npm run build

build: off

version: "{build}"

matrix:
  fast_finish: true